# Generated by Django 3.1.3 on 2020-11-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkWithProjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='aurhors',
        ),
    ]
