# Generated by Django 3.1.3 on 2020-11-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkWithProjects', '0003_project_aurhors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='aurhors',
            new_name='authors',
        ),
    ]
